wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.7
    start_time: 1676210222.773144
    t:
      1:
      - 2
      - 3
      - 55
      3:
      - 23
      4: 3.10.7
      5: 0.13.10
      8:
      - 1
      - 5
